# Generated by Django 5.0.6 on 2024-05-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("graduation", "0001_initial"),
        ("school", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_id",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        default="A",
                        max_length=1,
                        verbose_name="Identificador",
                    ),
                ),
                (
                    "interval_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Inicio do intervalo"
                    ),
                ),
                (
                    "interval_duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duração do Intervalo"
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.classroom",
                        verbose_name="Sala de Aula",
                    ),
                ),
                (
                    "graduation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graduation.graduation",
                        verbose_name="Graduação",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.schoolyear",
                        verbose_name="Ano Letivo",
                    ),
                ),
                (
                    "turn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.turnschool",
                        verbose_name="Turno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.CreateModel(
            name="GridGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_week",
                    models.CharField(
                        choices=[
                            ("sunday", "Domingo"),
                            ("monday", "Segunda-Feira"),
                            ("tuesday", "Terca-Feira"),
                            ("wednesday", "Quarta-Feira"),
                            ("thursday", "Quinta-Feira"),
                            ("friday", "Sexta-Feira"),
                            ("saturday", "Sábado"),
                        ],
                        max_length=15,
                        verbose_name="Dia da Semana",
                    ),
                ),
                ("time_start", models.TimeField(verbose_name="Horario inicial")),
                (
                    "duration_lesson",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Informe um intervalo em minutos",
                        verbose_name="Duração (minutos)",
                    ),
                ),
                (
                    "dicipline",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("math", "Matemática"),
                            ("history", "História"),
                            ("geography", "Geografia"),
                            ("science", "Ciência"),
                            ("art", "Artes"),
                            ("english", "Inglês"),
                            ("spanish", "Espanhol"),
                            ("french", "Francês"),
                            ("dramatics", "Dramartugia"),
                            ("physicaleducation", "Educação Física"),
                            ("woodshop", "Marcenaria"),
                            ("health", "Saúde"),
                            ("economics", "Econômia"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Diciplina",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=254, verbose_name="Descrição"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                        verbose_name="Professor",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="group.group",
                        verbose_name="Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "GripGroup",
                "verbose_name_plural": "GripGroups",
            },
        ),
    ]
