# Generated by Django 5.0.6 on 2024-05-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("school", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, verbose_name="Disciplina")),
                (
                    "disciplines",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="graduation.discipline",
                        verbose_name="Disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
            },
        ),
        migrations.CreateModel(
            name="Graduation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="Nome da Graduação"),
                ),
                (
                    "disciplines",
                    models.ManyToManyField(
                        to="graduation.discipline", verbose_name="Disciplinas"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="school.school",
                        verbose_name="Escola",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teacher.teacher",
                        verbose_name="Professor(a)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Graduação",
                "verbose_name_plural": "Gratuações",
            },
        ),
    ]
